package crypto

import (
	"context"
	"errors"
)

// ErrProviderNotConfigured is returned by key providers whose backing service
// integration has not been built or wired up in this deployment.
var ErrProviderNotConfigured = errors.New("crypto: key provider is not configured in this build")

// The types below stake out the shape of the managed key providers without
// pretending to implement them. They exist so that the interface can be
// validated against real KMS semantics now, while the actual clients are added
// with their SDK dependencies later.
//
// Each managed provider maps onto its service directly:
//
//	AWS KMS      Encrypt/Decrypt with EncryptionContext carrying encCtx verbatim.
//	GCP KMS      Encrypt/Decrypt with additionalAuthenticatedData set to the
//	             canonical serialization of encCtx.
//	Azure        Key Vault or Managed HSM wrapKey/unwrapKey; because Azure has no
//	             native encryption context, the binding is carried by wrapping the
//	             data key in a local AEAD layer keyed by the unwrapped result.
//
// In every case the data key is generated by the broker and the root key never
// leaves the service, which is what the KeyProvider interface was shaped for.

// AWSKMSProvider will wrap data keys using an AWS KMS customer managed key.
type AWSKMSProvider struct {
	// KeyARN identifies the customer managed key. Key rotation is tracked by
	// KMS itself; the ARN recorded per row remains sufficient to decrypt.
	KeyARN string
}

func (p *AWSKMSProvider) ActiveKeyID(context.Context) (string, error) {
	return "", ErrProviderNotConfigured
}

func (p *AWSKMSProvider) Wrap(context.Context, string, []byte, map[string]string) ([]byte, error) {
	return nil, ErrProviderNotConfigured
}

func (p *AWSKMSProvider) Unwrap(context.Context, string, []byte, map[string]string) ([]byte, error) {
	return nil, ErrProviderNotConfigured
}

func (p *AWSKMSProvider) Describe() string { return "aws-kms (not configured)" }

var _ KeyProvider = (*AWSKMSProvider)(nil)

// GCPKMSProvider will wrap data keys using a GCP Cloud KMS crypto key.
type GCPKMSProvider struct {
	// KeyName is the fully qualified crypto key resource name.
	KeyName string
}

func (p *GCPKMSProvider) ActiveKeyID(context.Context) (string, error) {
	return "", ErrProviderNotConfigured
}

func (p *GCPKMSProvider) Wrap(context.Context, string, []byte, map[string]string) ([]byte, error) {
	return nil, ErrProviderNotConfigured
}

func (p *GCPKMSProvider) Unwrap(context.Context, string, []byte, map[string]string) ([]byte, error) {
	return nil, ErrProviderNotConfigured
}

func (p *GCPKMSProvider) Describe() string { return "gcp-kms (not configured)" }

var _ KeyProvider = (*GCPKMSProvider)(nil)

// AzureKeyVaultProvider will wrap data keys using Azure Key Vault or Managed HSM.
type AzureKeyVaultProvider struct {
	// KeyIdentifier is the versioned key URL.
	KeyIdentifier string
}

func (p *AzureKeyVaultProvider) ActiveKeyID(context.Context) (string, error) {
	return "", ErrProviderNotConfigured
}

func (p *AzureKeyVaultProvider) Wrap(context.Context, string, []byte, map[string]string) ([]byte, error) {
	return nil, ErrProviderNotConfigured
}

func (p *AzureKeyVaultProvider) Unwrap(context.Context, string, []byte, map[string]string) ([]byte, error) {
	return nil, ErrProviderNotConfigured
}

func (p *AzureKeyVaultProvider) Describe() string { return "azure-keyvault (not configured)" }

var _ KeyProvider = (*AzureKeyVaultProvider)(nil)
